config/routes.rb
Rails.application.routes.draw do

resources :projects
resources :works
resources :calendars


root "calendars#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base


	has_many :works
	belongs_to :customer

	accepts_nested_attributes_for :works,
										
										allow_destroy: true
 	

  validates :titolo, :customer_id, :stato, presence: true
end

app/models/technician.rb
class Technician < ActiveRecord::Base
	has_many :works
end

app/models/work.rb
class Work < ActiveRecord::Base
	belongs_to :project
	belongs_to :technician
	belongs_to :location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

	def index

		@year = Time.now.year
		@month = Time.now.month
			
			@anno = params[:anno]
			@mese = params[:mese]
			
			

		  @date = params[:mese] ? Time.new(@anno, @mese) : Time.new(@year,@month)

		 @day = Time.now.day
		
		 @day_s = sprintf ('%02d'), @day

		 if params[:mese].blank?
		 	@mese_n_g = @month
		 else
		 	@mese_n_g = @mese.to_i
		 end


		@days_in_month = Time.days_in_month(@mese_n_g, @year)
		@i = 0
		# @br = "</br>".html_safe

		if params[:technician_id].blank? && params[:esterno].blank?
			@works = Work.all
			@w = 0

		elsif params[:esterno].present?
			@works = Work.where.not(:technician_id => ['1','2','3','4'])
			@w = 1
		else
			@works = Work.where(:technician_id => params[:technician_id])
			@w = 1
		end


		@rapportino = Work.all.order('datetimeperformed asc')
		@rapportinoStage = Work.where(:technician_id => 1)
	
	end

	def show
		@work = Work.find(params[:id])
	end

	def new
		@work = Work.new
	end

	def create
		@work = Work.new(params[:work].permit(:project_id, :technician_id, :location_id, :activity, :datetimeperformed, :hours, :column,:orepreventivate))
		respond_to do |format|
			if @work.save
				format.html { redirect_to works_path, notice: 'Lavoro Creato' }
				format.js { }
			else
				format.html { render 'new' }
				format.js { }
			end
		end
	end

	def edit
		@work = Work.find(params[:id])
	end

	def update
		@work = Work.find(params[:id])

		if @work.update(params[:work].permit(:project_id, :technician_id, :location_id, :activity, :datetimeperformed, :hours, :column,:orepreventivate))
			flash[:notice] = 'Lavoro Aggiornato'
			respond_to @work do |format|
				format.html {redirect_to @work}
				format.js
			end
		else
			render 'edit'
		end
	end

def only_admins_create_update_work
	redirect_to works_path, :alert => 'solo gli amministratori possono creare un lavoro' unless current_user.admin
	
end

def delete
	@work = Work.find(params[:id])
end
def destroy
	work = Work.find(params[:id])
    work.destroy
    redirect_to(:action => 'index')
end




end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]

	def index
		@project = Project.all.order("created_at DESC")
	end

	def show
	end

	def new
		@project = Project.new

	end

	def create
		@project = Project.new(project_params)

		if @project.save
			redirect_to @project, notice: "Progetto creato con successo!"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @project.update(project_params)
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to root_path, notice: "Progetto cancellato con successo!"
	end


	private 

	def project_params
		params.require(:project).permit(:titolo, :customer_id, :stato, works_attributes: [:id, :data, :activity, :column, :location_id, :technician_id, :_destroy])
	end

	def find_project
		@project = Project.find(params[:id])
	end


end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
	
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/calendars/index.html.erb
<h2 >
    <%= link_to "<", :mese => (@date.beginning_of_month-1).strftime("%m"), :anno => (@date.beginning_of_month-1).strftime("%Y") %>

   	<% if @date.strftime("%m") == '01' %>
   		<%= 'GENNAIO' %>
   	<% elsif @date.strftime("%m") == '02' %>
   		<%= 'FEBBRAIO' %>
   	<% elsif @date.strftime("%m") == '03' %>
   		<%= 'MARZO' %>
   	<% elsif @date.strftime("%m") == '04' %>
   		<%= 'APRILE' %>
   	<% elsif @date.strftime("%m") == '05' %>
   		<%= 'MAGGIO' %>
   	<% elsif @date.strftime("%m") == '06' %>
   		<%= 'GIUGNO' %>
   	<% elsif @date.strftime("%m") == '07' %>
   		<%= 'LUGLIO' %>
   	<% elsif @date.strftime("%m") == '08' %>
   		<%= 'AGOSTO' %>
   	<% elsif @date.strftime("%m") == '09' %>
   		<%= 'SETTEMBRE' %>
   	<% elsif @date.strftime("%m") == '10' %>
   		<%= 'OTTOBRE' %>
   	<% elsif @date.strftime("%m") == '11' %>
   		<%= 'NOVEMBRE' %>
   	<% elsif @date.strftime("%m") == '12' %>
   		<%= 'DICEMBRE' %>
   	<% end %>

     <%= @date.strftime("%Y") %>
    <%= link_to ">", :mese => (@date.end_of_month+1).strftime("%m"), :anno => (@date.end_of_month+1).strftime("%Y") %>
  </h2>


<h4 class = "modific" ><%= link_to 'Nuovo lavoro', new_project_path, id:'new_link', remote: true %></h4>

<%= link_to 'Stage', calendars_path(technician_id: 1, mese: params[:mese], anno: params[:anno]) %>
<%= link_to 'Simo', calendars_path(technician_id: 2, mese: params[:mese], anno: params[:anno] ) %>
<%= link_to 'Andrea', calendars_path(technician_id: 3, mese: params[:mese], anno: params[:anno] ) %>
<%= link_to 'Loris', calendars_path(technician_id: 4, mese: params[:mese], anno: params[:anno] ) %>
<%= link_to 'Esterni', calendars_path(esterno: true, mese: params[:mese], anno: params[:anno] ) %>








<table class="table table-bordered">
	<tbody>
		<tr>
				<th id = 'data' colspan = '2'>Data</th>
				<th class = 'location' >Verdi</th>
				<th id = 'custodia' >c</th>
				<th class = 'location' >Azzano</th>
				<th id = 'custodia' >c</th>
				<th class = 'location' >Fiera</th>
				<th id = 'custodia' >c</th>
				<th class = 'location' >Maniago</th>
				<th id = 'custodia' >c</th>
				<th class = 'location' >Cordenons</th>
				<th class = 'location' >Auditorium</th>
				<th class = 'location'  >Pordenone</th>
				<th class = 'location' >fuori Pordenone</th>
				<th class = 'location' >altro 1</th>
				<th class = 'location' >altro 2</th>
		</tr>


	<% loop do %>
		<% @i += 1 %>
		<% break if @i > @days_in_month %>
		
			<% @dd = sprintf ('%02d'), @i %>
			<% if @dd == @day_s && @date.strftime("%m").to_i == Time.now.month && @date.strftime("%Y").to_i == Time.now.year %>
			<tr id = "oggi">
			<% else %>
			<tr>
			<% end %>
				<td>
					<% @wDay = Time.new(@date.strftime("%Y"),@date.strftime("%m"),@dd ).strftime('%A') %>
					<% if @wDay == 'Monday' %>
					<%= 'l' %>
					<% end %>
					<% if @wDay == 'Tuesday' %>
					<%= 'm' %>
					<% end %>
					<% if @wDay == 'Wednesday' %>
					<%= 'm' %>
					<% end %>
					<% if @wDay == 'Thursday' %>
					<%= 'g' %>
					<% end %>
					<% if @wDay == 'Friday' %>
					<%= 'v' %>
					<% end %>
					<% if @wDay == 'Saturday' %>
					<%= 's' %>
					<% end %>	
					<% if @wDay == 'Sunday' %>
					<%= 'd' %>
					<% end %>
				</td>
				<td>
					<%= @dd %>
				</td>
				
				<% l = ['verdi','custodiaVerdi','azzano', 'custodiaAzzano', 'fiera', 'custodiaFiera', 'maniago', 'custodiaManiago', 'cordenons', 'auditorium','altro Pn','altro Fuori PN','altro 1','altro 2'] %>
				

				<% l.each do |loc| %>
				<% v = @works.where(:column => loc) %>
				<% @macchinista  = 0 %>
				<% @elettricista  = 0 %>
				<% @fonico  = 0 %>
				<% @service  = 0 %>
				<% @facchini  = 0 %>
				<% @titoloP  = 0 %>
				<% @aiuti = 0 %>
				<% @noRepeatM = 0 %>
				<% @noRepeatE  = 0 %>
				<% @noRepeatF  = 0 %>
				<% @noRepeatP  = 0 %>
				<% @noRepeatService = 0 %>
				<% @meseCella = sprintf ('%02d'), @month %>
				<% if params[:mese].blank? && params[:ano].blank? %>
					<td  id = '<%= @dd  %><%= @meseCella %><%= @year %><%= loc %>'>
				<% else %>
					<td  id = '<%= @dd  %><%= params[:mese] %><%= params[:anno] %><%= loc %>'>
				<% end %>

				
				<%= link_to '&nbsp;'.html_safe , new_project_path, remote: true %>
				<% v.each do |w| %>
					<% @d = w.data.strftime('%d') %>
					<% @m = w.data.strftime('%m') %>
					<% @y = w.data.strftime('%Y') %>
					
					
					
						<% if @d == @dd && @m == @date.strftime("%m") && @y == @date.strftime("%Y")%>
								<% if loc == 'custodiaVerdi' || loc == 'custodiaAzzano' || loc == 'custodiaFiera' || loc == 'custodiaManiago'%>
								<% @p = 'xxx' %>
								<% else %>
								<% @p = Project.find(w.project_id).titolo %>
								<% end %>
								<% @id = w.project_id%>
									<% if @noRepeatP == 1 %>
									<% @titoloP += 1 %>
									<% else %>
									<% @titoloP += 1 %>
									<% @noRepeatP = 1 %>
									<h4 class = "titoloP"><%= link_to @p, project_path(@id) %></h4>
									
									<% end %>

								
								<% @t = w.activity %>
								
								<% if @t == 'macchinista'%>
									<% if @noRepeatM == 1 %>
									<% @macchinista += 1 %>
									<% else %>
									<% @macchinista += 1 %>
									<% @noRepeatM = 1 %>
									<% @mm = @t %>
									
									<% end %>
								<% end %>

								<% if @t == 'elettricista'%>
									<% if @noRepeatE == 1 %>
									<% @elettricista += 1 %>
									<% else %>
									<% @elettricista += 1 %>
									<% @noRepeatE = 1 %>
									<% @ee = @t %>
									
									
									<% end %>
								<% end %>


								<% if @t == 'fonico'%>
									<% if @noRepeatF == 1 %>
									<% @fonico += 1 %>
									<% else %>
									<% @fonico += 1 %>
									<% @noRepeatF = 1 %>
									<% @ff = @t %>
									
									
									<% end %>
								<% end %>

								<% if @t == 'service'%>
									<% @ls = w.column %>
									<% if @noRepeatService == 1 %>
									<% @service += 1 %>
									<% else %>
									<% @service += 1 %>
									<% @noRepeatService = 1 %>
									
									
									
									<% end %>
								<% end %>

								<% if @t == 'facchino' %>
								<% @facchini += 1 %>
								<% end %>
								<% if @t == 'custode' %>
									<%= 'c' %>
									<div class = "orario">orario custodia</div>
								<% end %>
							
							
							
							<% @l = loc %>
							
							
							
						<% end %>
						
						
					<% end %>
					</br>
					<% if @macchinista > 0 %>
					<% @aiuti = 1 %>
					<a class = "activity"><%= @macchinista %></a>
						<span style="font-weight:bold"><%= link_to 'M', project_path(@id) %></span>
						
					<% end %>
					<% if @elettricista > 0 %>
					<% @aiuti = 1 %>
						<a class = "activity"><%= @elettricista %></a>
						<span style="font-weight:bold"><%= link_to 'E', project_path(@id), :class => "activity" %></span>
						
					<% end %>

					<% if @fonico > 0  %>
					<% @aiuti = 1 %>
						<a class = "activity"><%= @fonico %></a>
						<span style="font-weight:bold"><%= link_to 'F', project_path(@id), :class => "activity" %></span>
						
					<% end %>

					
					<% if @facchini > 0%>
						
							(<%= link_to @facchini, project_path(@id) %>)
						
					<% end %>
					<% if @aiuti == 1 %>
					</br>
					<% else %>

					<% end %>
					<% if @service > 0 %>
						<a class = "activity"><%= @service %></a>
						<span style="font-weight:bold"><%= link_to 'sv', project_path(@id), :class => "activity" %></span>
						<%= @ls %>
						
					<% end %>
					
				</td>
				<% end %>
				<% @noRepeatM = 0 %>
				<% @noRepeatE = 0 %>
				<% @noRepeatF = 0 %>
				<% @noRepeatService = 0 %>
			</tr>
	
					
		
	<% end %>



</tbody>
</table>

<div id = "mod" >

</div>

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title time Claps
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "time Claps", root_path

		
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Nuovo Porgetto", new_project_path
				%li= link_to "Esci", root_path
			%ul.nav.navbar-nav.navbar-right
				%li= link_to "Registrati", root_path
				%li= link_to "Entra", root_path

	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert"

		= yield

app/views/projects/_form.html.haml
= simple_form_for @project, html: { multipart: true } do |f|
	- if @project.errors.any?
		#errors
			%p
				= @project.errors.count
				Prevented this project froms saving
			%ul
				- @project.errors.full_messages.each do |msg|
					%li= msg
	.panel-body
		= f.input :titolo, input_html: { class: 'form-control' }
		= f.collection_select(:customer_id, Customer.all, :id, :name, include_blank: true, class: 'form-control' )
		= f.input :stato, collection: [ "da preventivare", "da pagare", "pagato"], input_html: { class: 'form-control' }
		.row
			.col-md-6
				%h3 lavori
				#ingredients
					= f.simple_fields_for :works do |work|
						= render 'work_fields', f: work
					.links
						= link_to_add_association 'Aggiungi Lavoro', f, :works, class: "btn btn-default add-button"

			
	= f.button :submit, class: "btn btn-primary"

app/views/projects/_work_fields.html.haml
.form-inline.clearfix
	.nested-fields

		= f.date_select :data, input_html: { class: 'inline' }
		
		= f.input :activity, collection: [ "macchinista", "elettricista", "service", "facchino", "custode", "fonico"], input_html: { class: 'inline' }
		
		= f.collection_select(:technician_id, Technician.all, :id, :name, include_blank: true, class: 'inline' )
		= f.input :column, input_html: { class: 'inline' }
		= link_to_remove_association "Remove", f, class: "inline"

app/views/projects/edit.html.haml
%h1 Modifica Progetto
= render 'form'

app/views/projects/index.html.haml
- @project.each do |project|
	%h2= link_to project.titolo, project

app/views/projects/new.html.haml
%h1 Nuovo progetto
= render 'form'

%br/

= link_to "indietro", root_path, class: "btn btn-default"

app/views/projects/show.html.haml
.main_content
	#recipe_top.row
		
		.col-md-8
			#project_info
				%h1= @project.titolo
				%p.stato= @project.stato
				

	.row
		.col-md-
			#lavori
				%h2 Lavori:
				%table.table
					%tbody
						%tr
							%th data
							%th attività
							%th colonna
							%th loc
					- @project.works.each do |work|
						%tr
							%td= work.data.strftime("%d-%m-%Y")
							%td= work.activity
							%td= work.column
							%td= work.location_id

				
						


		
	.row
		.col-md-12
			= link_to "indietro", root_path, class: "btn btn-default"
			
			= link_to "Modifica", edit_project_path, class: "btn btn-default"
			= link_to "Cancella", project_path, method: :delete, data: {confirm: "Sei sicuro?" }, class: "btn btn-default"